<?php defined('SYSPATH') OR die('No direct script access.'); ?>

2013-10-24 09:09:31 --- CRITICAL: ErrorException [ 8 ]: Undefined variable: departements ~ APPPATH\views\pages\add.php [ 26 ] in C:\wamp\www\FreeAds\application\views\pages\add.php:26
2013-10-24 09:09:31 --- DEBUG: #0 C:\wamp\www\FreeAds\application\views\pages\add.php(26): Kohana_Core::error_handler(8, 'Undefined varia...', 'C:\wamp\www\Fre...', 26, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#2 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#3 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(228): Kohana_View->render()
#4 C:\wamp\www\FreeAds\application\views\template.php(130): Kohana_View->__toString()
#5 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#6 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#7 C:\wamp\www\FreeAds\system\classes\Kohana\Controller\Template.php(44): Kohana_View->render()
#8 C:\wamp\www\FreeAds\application\classes\Controller\demo.php(50): Kohana_Controller_Template->after()
#9 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(87): Controller_Demo->after()
#10 [internal function]: Kohana_Controller->execute()
#11 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Annonces))
#12 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#13 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#14 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#15 {main} in C:\wamp\www\FreeAds\application\views\pages\add.php:26
2013-10-24 09:10:21 --- CRITICAL: ErrorException [ 8 ]: Undefined variable: departements ~ APPPATH\views\pages\add.php [ 26 ] in C:\wamp\www\FreeAds\application\views\pages\add.php:26
2013-10-24 09:10:21 --- DEBUG: #0 C:\wamp\www\FreeAds\application\views\pages\add.php(26): Kohana_Core::error_handler(8, 'Undefined varia...', 'C:\wamp\www\Fre...', 26, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#2 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#3 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(228): Kohana_View->render()
#4 C:\wamp\www\FreeAds\application\views\template.php(130): Kohana_View->__toString()
#5 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#6 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#7 C:\wamp\www\FreeAds\system\classes\Kohana\Controller\Template.php(44): Kohana_View->render()
#8 C:\wamp\www\FreeAds\application\classes\Controller\demo.php(50): Kohana_Controller_Template->after()
#9 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(87): Controller_Demo->after()
#10 [internal function]: Kohana_Controller->execute()
#11 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Annonces))
#12 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#13 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#14 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#15 {main} in C:\wamp\www\FreeAds\application\views\pages\add.php:26
2013-10-24 09:32:36 --- CRITICAL: ErrorException [ 1 ]: Class 'Model_categories' not found ~ MODPATH\orm\classes\Kohana\ORM.php [ 46 ] in file:line
2013-10-24 09:32:36 --- DEBUG: #0 [internal function]: Kohana_Core::shutdown_handler()
#1 {main} in file:line
2013-10-24 10:05:54 --- CRITICAL: ErrorException [ 8 ]: Undefined variable: users ~ APPPATH\views\template.php [ 23 ] in C:\wamp\www\FreeAds\application\views\template.php:23
2013-10-24 10:05:54 --- DEBUG: #0 C:\wamp\www\FreeAds\application\views\template.php(23): Kohana_Core::error_handler(8, 'Undefined varia...', 'C:\wamp\www\Fre...', 23, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#2 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#3 C:\wamp\www\FreeAds\system\classes\Kohana\Controller\Template.php(44): Kohana_View->render()
#4 C:\wamp\www\FreeAds\application\classes\Controller\demo.php(50): Kohana_Controller_Template->after()
#5 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(87): Controller_Demo->after()
#6 [internal function]: Kohana_Controller->execute()
#7 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Annonces))
#8 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#9 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#10 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#11 {main} in C:\wamp\www\FreeAds\application\views\template.php:23
2013-10-24 10:07:41 --- CRITICAL: ErrorException [ 8 ]: Undefined property: Controller_Annonces::$params ~ APPPATH\classes\Controller\annonces.php [ 34 ] in C:\wamp\www\FreeAds\application\classes\Controller\annonces.php:34
2013-10-24 10:07:41 --- DEBUG: #0 C:\wamp\www\FreeAds\application\classes\Controller\annonces.php(34): Kohana_Core::error_handler(8, 'Undefined prope...', 'C:\wamp\www\Fre...', 34, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(84): Controller_Annonces->action_add()
#2 [internal function]: Kohana_Controller->execute()
#3 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Annonces))
#4 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#5 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#6 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#7 {main} in C:\wamp\www\FreeAds\application\classes\Controller\annonces.php:34
2013-10-24 10:08:07 --- CRITICAL: ErrorException [ 8 ]: Undefined property: Request::$params ~ APPPATH\classes\Controller\annonces.php [ 34 ] in C:\wamp\www\FreeAds\application\classes\Controller\annonces.php:34
2013-10-24 10:08:07 --- DEBUG: #0 C:\wamp\www\FreeAds\application\classes\Controller\annonces.php(34): Kohana_Core::error_handler(8, 'Undefined prope...', 'C:\wamp\www\Fre...', 34, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(84): Controller_Annonces->action_add()
#2 [internal function]: Kohana_Controller->execute()
#3 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Annonces))
#4 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#5 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#6 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#7 {main} in C:\wamp\www\FreeAds\application\classes\Controller\annonces.php:34
2013-10-24 10:08:34 --- CRITICAL: ErrorException [ 4 ]: syntax error, unexpected '(', expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' ~ APPPATH\classes\Controller\annonces.php [ 34 ] in file:line
2013-10-24 10:08:34 --- DEBUG: #0 [internal function]: Kohana_Core::shutdown_handler()
#1 {main} in file:line
2013-10-24 10:16:22 --- CRITICAL: View_Exception [ 0 ]: The requested view pages/add/21 could not be found ~ SYSPATH\classes\Kohana\View.php [ 257 ] in C:\wamp\www\FreeAds\system\classes\Kohana\View.php:137
2013-10-24 10:16:22 --- DEBUG: #0 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(137): Kohana_View->set_filename('pages/add/21')
#1 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(30): Kohana_View->__construct('pages/add/21', NULL)
#2 C:\wamp\www\FreeAds\application\classes\Controller\annonces.php(12): Kohana_View::factory('pages/add/21')
#3 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(84): Controller_Annonces->action_add()
#4 [internal function]: Kohana_Controller->execute()
#5 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Annonces))
#6 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#7 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#8 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#9 {main} in C:\wamp\www\FreeAds\system\classes\Kohana\View.php:137
2013-10-24 10:24:13 --- CRITICAL: ErrorException [ 8 ]: Undefined variable: users ~ APPPATH\views\pages\add.php [ 10 ] in C:\wamp\www\FreeAds\application\views\pages\add.php:10
2013-10-24 10:24:13 --- DEBUG: #0 C:\wamp\www\FreeAds\application\views\pages\add.php(10): Kohana_Core::error_handler(8, 'Undefined varia...', 'C:\wamp\www\Fre...', 10, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#2 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#3 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(228): Kohana_View->render()
#4 C:\wamp\www\FreeAds\application\views\template.php(130): Kohana_View->__toString()
#5 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#6 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#7 C:\wamp\www\FreeAds\system\classes\Kohana\Controller\Template.php(44): Kohana_View->render()
#8 C:\wamp\www\FreeAds\application\classes\Controller\demo.php(50): Kohana_Controller_Template->after()
#9 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(87): Controller_Demo->after()
#10 [internal function]: Kohana_Controller->execute()
#11 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Annonces))
#12 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#13 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#14 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#15 {main} in C:\wamp\www\FreeAds\application\views\pages\add.php:10
2013-10-24 10:57:06 --- CRITICAL: ErrorException [ 8 ]: Undefined variable: list ~ APPPATH\classes\Controller\annonces.php [ 8 ] in C:\wamp\www\FreeAds\application\classes\Controller\annonces.php:8
2013-10-24 10:57:06 --- DEBUG: #0 C:\wamp\www\FreeAds\application\classes\Controller\annonces.php(8): Kohana_Core::error_handler(8, 'Undefined varia...', 'C:\wamp\www\Fre...', 8, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(84): Controller_Annonces->action_list()
#2 [internal function]: Kohana_Controller->execute()
#3 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Annonces))
#4 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#5 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#6 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#7 {main} in C:\wamp\www\FreeAds\application\classes\Controller\annonces.php:8
2013-10-24 10:57:26 --- CRITICAL: Kohana_Exception [ 0 ]: The name property does not exist in the Model_Annonce class ~ MODPATH\orm\classes\Kohana\ORM.php [ 687 ] in C:\wamp\www\FreeAds\modules\orm\classes\Kohana\ORM.php:603
2013-10-24 10:57:26 --- DEBUG: #0 C:\wamp\www\FreeAds\modules\orm\classes\Kohana\ORM.php(603): Kohana_ORM->get('name')
#1 C:\wamp\www\FreeAds\application\views\pages\annonceslist.php(15): Kohana_ORM->__get('name')
#2 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#3 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#4 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(228): Kohana_View->render()
#5 C:\wamp\www\FreeAds\application\views\template.php(130): Kohana_View->__toString()
#6 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#7 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#8 C:\wamp\www\FreeAds\system\classes\Kohana\Controller\Template.php(44): Kohana_View->render()
#9 C:\wamp\www\FreeAds\application\classes\Controller\demo.php(50): Kohana_Controller_Template->after()
#10 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(87): Controller_Demo->after()
#11 [internal function]: Kohana_Controller->execute()
#12 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Annonces))
#13 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#14 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#15 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#16 {main} in C:\wamp\www\FreeAds\modules\orm\classes\Kohana\ORM.php:603
2013-10-24 11:24:26 --- CRITICAL: ErrorException [ 4 ]: syntax error, unexpected '*', expecting ')' ~ APPPATH\classes\Controller\annonces.php [ 7 ] in file:line
2013-10-24 11:24:26 --- DEBUG: #0 [internal function]: Kohana_Core::shutdown_handler()
#1 {main} in file:line
2013-10-24 11:26:29 --- CRITICAL: ErrorException [ 8 ]: Undefined variable: list ~ APPPATH\classes\Controller\annonces.php [ 8 ] in C:\wamp\www\FreeAds\application\classes\Controller\annonces.php:8
2013-10-24 11:26:29 --- DEBUG: #0 C:\wamp\www\FreeAds\application\classes\Controller\annonces.php(8): Kohana_Core::error_handler(8, 'Undefined varia...', 'C:\wamp\www\Fre...', 8, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(84): Controller_Annonces->action_list()
#2 [internal function]: Kohana_Controller->execute()
#3 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Annonces))
#4 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#5 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#6 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#7 {main} in C:\wamp\www\FreeAds\application\classes\Controller\annonces.php:8
2013-10-24 11:54:09 --- CRITICAL: ErrorException [ 8 ]: Undefined variable: categories ~ APPPATH\views\pages\add.php [ 40 ] in C:\wamp\www\FreeAds\application\views\pages\add.php:40
2013-10-24 11:54:09 --- DEBUG: #0 C:\wamp\www\FreeAds\application\views\pages\add.php(40): Kohana_Core::error_handler(8, 'Undefined varia...', 'C:\wamp\www\Fre...', 40, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#2 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#3 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(228): Kohana_View->render()
#4 C:\wamp\www\FreeAds\application\views\template.php(130): Kohana_View->__toString()
#5 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#6 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#7 C:\wamp\www\FreeAds\system\classes\Kohana\Controller\Template.php(44): Kohana_View->render()
#8 C:\wamp\www\FreeAds\application\classes\Controller\demo.php(50): Kohana_Controller_Template->after()
#9 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(87): Controller_Demo->after()
#10 [internal function]: Kohana_Controller->execute()
#11 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Annonces))
#12 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#13 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#14 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#15 {main} in C:\wamp\www\FreeAds\application\views\pages\add.php:40
2013-10-24 11:55:24 --- CRITICAL: ErrorException [ 8 ]: Undefined variable: categories ~ APPPATH\views\pages\add.php [ 40 ] in C:\wamp\www\FreeAds\application\views\pages\add.php:40
2013-10-24 11:55:24 --- DEBUG: #0 C:\wamp\www\FreeAds\application\views\pages\add.php(40): Kohana_Core::error_handler(8, 'Undefined varia...', 'C:\wamp\www\Fre...', 40, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#2 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#3 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(228): Kohana_View->render()
#4 C:\wamp\www\FreeAds\application\views\template.php(130): Kohana_View->__toString()
#5 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#6 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#7 C:\wamp\www\FreeAds\system\classes\Kohana\Controller\Template.php(44): Kohana_View->render()
#8 C:\wamp\www\FreeAds\application\classes\Controller\demo.php(50): Kohana_Controller_Template->after()
#9 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(87): Controller_Demo->after()
#10 [internal function]: Kohana_Controller->execute()
#11 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Annonces))
#12 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#13 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#14 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#15 {main} in C:\wamp\www\FreeAds\application\views\pages\add.php:40
2013-10-24 12:03:25 --- CRITICAL: ErrorException [ 4 ]: syntax error, unexpected 'echo' (T_ECHO) ~ APPPATH\classes\Controller\annonces.php [ 48 ] in file:line
2013-10-24 12:03:25 --- DEBUG: #0 [internal function]: Kohana_Core::shutdown_handler()
#1 {main} in file:line
2013-10-24 14:38:42 --- CRITICAL: ErrorException [ 1 ]: Using $this when not in object context ~ APPPATH\views\pages\ownannonces.php [ 2 ] in file:line
2013-10-24 14:38:42 --- DEBUG: #0 [internal function]: Kohana_Core::shutdown_handler()
#1 {main} in file:line
2013-10-24 15:36:04 --- CRITICAL: ErrorException [ 8 ]: Undefined variable: list ~ APPPATH\views\pages\ownannonces.php [ 5 ] in C:\wamp\www\FreeAds\application\views\pages\ownannonces.php:5
2013-10-24 15:36:04 --- DEBUG: #0 C:\wamp\www\FreeAds\application\views\pages\ownannonces.php(5): Kohana_Core::error_handler(8, 'Undefined varia...', 'C:\wamp\www\Fre...', 5, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#2 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#3 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(228): Kohana_View->render()
#4 C:\wamp\www\FreeAds\application\views\template.php(139): Kohana_View->__toString()
#5 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#6 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#7 C:\wamp\www\FreeAds\system\classes\Kohana\Controller\Template.php(44): Kohana_View->render()
#8 C:\wamp\www\FreeAds\application\classes\Controller\demo.php(50): Kohana_Controller_Template->after()
#9 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(87): Controller_Demo->after()
#10 [internal function]: Kohana_Controller->execute()
#11 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Annonces))
#12 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#13 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#14 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#15 {main} in C:\wamp\www\FreeAds\application\views\pages\ownannonces.php:5
2013-10-24 15:36:23 --- CRITICAL: ErrorException [ 8 ]: Undefined variable: list ~ APPPATH\views\pages\ownannonces.php [ 5 ] in C:\wamp\www\FreeAds\application\views\pages\ownannonces.php:5
2013-10-24 15:36:23 --- DEBUG: #0 C:\wamp\www\FreeAds\application\views\pages\ownannonces.php(5): Kohana_Core::error_handler(8, 'Undefined varia...', 'C:\wamp\www\Fre...', 5, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#2 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#3 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(228): Kohana_View->render()
#4 C:\wamp\www\FreeAds\application\views\template.php(139): Kohana_View->__toString()
#5 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#6 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#7 C:\wamp\www\FreeAds\system\classes\Kohana\Controller\Template.php(44): Kohana_View->render()
#8 C:\wamp\www\FreeAds\application\classes\Controller\demo.php(50): Kohana_Controller_Template->after()
#9 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(87): Controller_Demo->after()
#10 [internal function]: Kohana_Controller->execute()
#11 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Annonces))
#12 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#13 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#14 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#15 {main} in C:\wamp\www\FreeAds\application\views\pages\ownannonces.php:5
2013-10-24 15:36:50 --- CRITICAL: ErrorException [ 2 ]: Invalid argument supplied for foreach() ~ APPPATH\views\pages\ownannonces.php [ 5 ] in C:\wamp\www\FreeAds\application\views\pages\ownannonces.php:5
2013-10-24 15:36:50 --- DEBUG: #0 C:\wamp\www\FreeAds\application\views\pages\ownannonces.php(5): Kohana_Core::error_handler(2, 'Invalid argumen...', 'C:\wamp\www\Fre...', 5, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#2 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#3 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(228): Kohana_View->render()
#4 C:\wamp\www\FreeAds\application\views\template.php(139): Kohana_View->__toString()
#5 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#6 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#7 C:\wamp\www\FreeAds\system\classes\Kohana\Controller\Template.php(44): Kohana_View->render()
#8 C:\wamp\www\FreeAds\application\classes\Controller\demo.php(50): Kohana_Controller_Template->after()
#9 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(87): Controller_Demo->after()
#10 [internal function]: Kohana_Controller->execute()
#11 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Annonces))
#12 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#13 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#14 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#15 {main} in C:\wamp\www\FreeAds\application\views\pages\ownannonces.php:5
2013-10-24 15:37:04 --- CRITICAL: ErrorException [ 2 ]: Invalid argument supplied for foreach() ~ APPPATH\views\pages\ownannonces.php [ 5 ] in C:\wamp\www\FreeAds\application\views\pages\ownannonces.php:5
2013-10-24 15:37:04 --- DEBUG: #0 C:\wamp\www\FreeAds\application\views\pages\ownannonces.php(5): Kohana_Core::error_handler(2, 'Invalid argumen...', 'C:\wamp\www\Fre...', 5, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#2 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#3 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(228): Kohana_View->render()
#4 C:\wamp\www\FreeAds\application\views\template.php(139): Kohana_View->__toString()
#5 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#6 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#7 C:\wamp\www\FreeAds\system\classes\Kohana\Controller\Template.php(44): Kohana_View->render()
#8 C:\wamp\www\FreeAds\application\classes\Controller\demo.php(50): Kohana_Controller_Template->after()
#9 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(87): Controller_Demo->after()
#10 [internal function]: Kohana_Controller->execute()
#11 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Annonces))
#12 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#13 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#14 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#15 {main} in C:\wamp\www\FreeAds\application\views\pages\ownannonces.php:5
2013-10-24 15:39:03 --- CRITICAL: ErrorException [ 4 ]: syntax error, unexpected ''/'' (T_CONSTANT_ENCAPSED_STRING) ~ APPPATH\classes\Controller\annonces.php [ 48 ] in file:line
2013-10-24 15:39:03 --- DEBUG: #0 [internal function]: Kohana_Core::shutdown_handler()
#1 {main} in file:line
2013-10-24 15:39:09 --- CRITICAL: ErrorException [ 4 ]: syntax error, unexpected ''/'' (T_CONSTANT_ENCAPSED_STRING) ~ APPPATH\classes\Controller\annonces.php [ 48 ] in file:line
2013-10-24 15:39:09 --- DEBUG: #0 [internal function]: Kohana_Core::shutdown_handler()
#1 {main} in file:line
2013-10-24 15:42:36 --- CRITICAL: ErrorException [ 4 ]: syntax error, unexpected 'pages' (T_STRING) ~ APPPATH\classes\Controller\annonces.php [ 53 ] in file:line
2013-10-24 15:42:36 --- DEBUG: #0 [internal function]: Kohana_Core::shutdown_handler()
#1 {main} in file:line
2013-10-24 18:56:13 --- CRITICAL: ErrorException [ 8 ]: Undefined variable: list ~ APPPATH\views\pages\ownannonces.php [ 5 ] in C:\wamp\www\FreeAds\application\views\pages\ownannonces.php:5
2013-10-24 18:56:13 --- DEBUG: #0 C:\wamp\www\FreeAds\application\views\pages\ownannonces.php(5): Kohana_Core::error_handler(8, 'Undefined varia...', 'C:\wamp\www\Fre...', 5, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#2 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#3 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(228): Kohana_View->render()
#4 C:\wamp\www\FreeAds\application\views\template.php(139): Kohana_View->__toString()
#5 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#6 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#7 C:\wamp\www\FreeAds\system\classes\Kohana\Controller\Template.php(44): Kohana_View->render()
#8 C:\wamp\www\FreeAds\application\classes\Controller\demo.php(50): Kohana_Controller_Template->after()
#9 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(87): Controller_Demo->after()
#10 [internal function]: Kohana_Controller->execute()
#11 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Annonces))
#12 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#13 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#14 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#15 {main} in C:\wamp\www\FreeAds\application\views\pages\ownannonces.php:5
2013-10-24 19:02:16 --- CRITICAL: Kohana_Exception [ 0 ]: Cannot update annonce model because it is not loaded. ~ MODPATH\orm\classes\Kohana\ORM.php [ 1357 ] in C:\wamp\www\FreeAds\application\classes\Controller\annonces.php:115
2013-10-24 19:02:16 --- DEBUG: #0 C:\wamp\www\FreeAds\application\classes\Controller\annonces.php(115): Kohana_ORM->update()
#1 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(84): Controller_Annonces->action_update()
#2 [internal function]: Kohana_Controller->execute()
#3 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Annonces))
#4 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#5 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#6 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#7 {main} in C:\wamp\www\FreeAds\application\classes\Controller\annonces.php:115
2013-10-24 19:02:53 --- CRITICAL: Kohana_Exception [ 0 ]: Cannot update annonce model because it is not loaded. ~ MODPATH\orm\classes\Kohana\ORM.php [ 1357 ] in C:\wamp\www\FreeAds\application\classes\Controller\annonces.php:115
2013-10-24 19:02:53 --- DEBUG: #0 C:\wamp\www\FreeAds\application\classes\Controller\annonces.php(115): Kohana_ORM->update()
#1 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(84): Controller_Annonces->action_update()
#2 [internal function]: Kohana_Controller->execute()
#3 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Annonces))
#4 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#5 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#6 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#7 {main} in C:\wamp\www\FreeAds\application\classes\Controller\annonces.php:115
2013-10-24 19:04:08 --- CRITICAL: Kohana_Exception [ 0 ]: Cannot update annonce model because it is not loaded. ~ MODPATH\orm\classes\Kohana\ORM.php [ 1357 ] in C:\wamp\www\FreeAds\application\classes\Controller\annonces.php:116
2013-10-24 19:04:08 --- DEBUG: #0 C:\wamp\www\FreeAds\application\classes\Controller\annonces.php(116): Kohana_ORM->update()
#1 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(84): Controller_Annonces->action_update()
#2 [internal function]: Kohana_Controller->execute()
#3 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Annonces))
#4 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#5 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#6 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#7 {main} in C:\wamp\www\FreeAds\application\classes\Controller\annonces.php:116
2013-10-24 19:06:02 --- CRITICAL: ErrorException [ 8 ]: Undefined variable: annonce ~ APPPATH\classes\Controller\annonces.php [ 110 ] in C:\wamp\www\FreeAds\application\classes\Controller\annonces.php:110
2013-10-24 19:06:02 --- DEBUG: #0 C:\wamp\www\FreeAds\application\classes\Controller\annonces.php(110): Kohana_Core::error_handler(8, 'Undefined varia...', 'C:\wamp\www\Fre...', 110, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(84): Controller_Annonces->action_update()
#2 [internal function]: Kohana_Controller->execute()
#3 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Annonces))
#4 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#5 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#6 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#7 {main} in C:\wamp\www\FreeAds\application\classes\Controller\annonces.php:110
2013-10-24 19:07:05 --- CRITICAL: ErrorException [ 2 ]: Creating default object from empty value ~ APPPATH\classes\Controller\annonces.php [ 116 ] in C:\wamp\www\FreeAds\application\classes\Controller\annonces.php:116
2013-10-24 19:07:05 --- DEBUG: #0 C:\wamp\www\FreeAds\application\classes\Controller\annonces.php(116): Kohana_Core::error_handler(2, 'Creating defaul...', 'C:\wamp\www\Fre...', 116, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(84): Controller_Annonces->action_update()
#2 [internal function]: Kohana_Controller->execute()
#3 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Annonces))
#4 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#5 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#6 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#7 {main} in C:\wamp\www\FreeAds\application\classes\Controller\annonces.php:116
2013-10-24 19:07:14 --- CRITICAL: ErrorException [ 8 ]: Undefined variable: list ~ APPPATH\views\pages\ownannonces.php [ 5 ] in C:\wamp\www\FreeAds\application\views\pages\ownannonces.php:5
2013-10-24 19:07:14 --- DEBUG: #0 C:\wamp\www\FreeAds\application\views\pages\ownannonces.php(5): Kohana_Core::error_handler(8, 'Undefined varia...', 'C:\wamp\www\Fre...', 5, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#2 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#3 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(228): Kohana_View->render()
#4 C:\wamp\www\FreeAds\application\views\template.php(139): Kohana_View->__toString()
#5 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#6 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#7 C:\wamp\www\FreeAds\system\classes\Kohana\Controller\Template.php(44): Kohana_View->render()
#8 C:\wamp\www\FreeAds\application\classes\Controller\demo.php(50): Kohana_Controller_Template->after()
#9 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(87): Controller_Demo->after()
#10 [internal function]: Kohana_Controller->execute()
#11 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Annonces))
#12 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#13 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#14 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#15 {main} in C:\wamp\www\FreeAds\application\views\pages\ownannonces.php:5
2013-10-24 19:08:23 --- CRITICAL: ErrorException [ 4 ]: syntax error, unexpected '}', expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' ~ APPPATH\classes\Controller\annonces.php [ 121 ] in file:line
2013-10-24 19:08:23 --- DEBUG: #0 [internal function]: Kohana_Core::shutdown_handler()
#1 {main} in file:line
2013-10-24 19:08:33 --- CRITICAL: ErrorException [ 2 ]: Invalid argument supplied for foreach() ~ APPPATH\views\pages\ownannonces.php [ 5 ] in C:\wamp\www\FreeAds\application\views\pages\ownannonces.php:5
2013-10-24 19:08:33 --- DEBUG: #0 C:\wamp\www\FreeAds\application\views\pages\ownannonces.php(5): Kohana_Core::error_handler(2, 'Invalid argumen...', 'C:\wamp\www\Fre...', 5, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#2 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#3 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(228): Kohana_View->render()
#4 C:\wamp\www\FreeAds\application\views\template.php(139): Kohana_View->__toString()
#5 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#6 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#7 C:\wamp\www\FreeAds\system\classes\Kohana\Controller\Template.php(44): Kohana_View->render()
#8 C:\wamp\www\FreeAds\application\classes\Controller\demo.php(50): Kohana_Controller_Template->after()
#9 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(87): Controller_Demo->after()
#10 [internal function]: Kohana_Controller->execute()
#11 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Annonces))
#12 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#13 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#14 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#15 {main} in C:\wamp\www\FreeAds\application\views\pages\ownannonces.php:5
2013-10-24 19:09:43 --- CRITICAL: ErrorException [ 8 ]: Undefined variable: list ~ APPPATH\classes\Controller\annonces.php [ 102 ] in C:\wamp\www\FreeAds\application\classes\Controller\annonces.php:102
2013-10-24 19:09:43 --- DEBUG: #0 C:\wamp\www\FreeAds\application\classes\Controller\annonces.php(102): Kohana_Core::error_handler(8, 'Undefined varia...', 'C:\wamp\www\Fre...', 102, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(84): Controller_Annonces->action_update()
#2 [internal function]: Kohana_Controller->execute()
#3 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Annonces))
#4 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#5 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#6 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#7 {main} in C:\wamp\www\FreeAds\application\classes\Controller\annonces.php:102
2013-10-24 19:10:15 --- CRITICAL: ErrorException [ 8 ]: Undefined variable: id ~ APPPATH\classes\Controller\annonces.php [ 102 ] in C:\wamp\www\FreeAds\application\classes\Controller\annonces.php:102
2013-10-24 19:10:15 --- DEBUG: #0 C:\wamp\www\FreeAds\application\classes\Controller\annonces.php(102): Kohana_Core::error_handler(8, 'Undefined varia...', 'C:\wamp\www\Fre...', 102, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(84): Controller_Annonces->action_update()
#2 [internal function]: Kohana_Controller->execute()
#3 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Annonces))
#4 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#5 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#6 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#7 {main} in C:\wamp\www\FreeAds\application\classes\Controller\annonces.php:102
2013-10-24 19:46:26 --- CRITICAL: ErrorException [ 8 ]: Undefined variable: value ~ APPPATH\classes\Controller\annonces.php [ 118 ] in C:\wamp\www\FreeAds\application\classes\Controller\annonces.php:118
2013-10-24 19:46:26 --- DEBUG: #0 C:\wamp\www\FreeAds\application\classes\Controller\annonces.php(118): Kohana_Core::error_handler(8, 'Undefined varia...', 'C:\wamp\www\Fre...', 118, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(84): Controller_Annonces->action_update()
#2 [internal function]: Kohana_Controller->execute()
#3 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Annonces))
#4 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#5 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#6 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#7 {main} in C:\wamp\www\FreeAds\application\classes\Controller\annonces.php:118
2013-10-24 22:36:59 --- CRITICAL: Database_Exception [ 1146 ]: Table 'freeads.username' doesn't exist [ INSERT INTO `annonces` (`titre`, `content`, `prix`, `region`, `categorie`, `posted_by`) VALUES ('Sdqsd', 'sqdqsdqs', '1212', '03 - Allier', 'MAISON', (SELECT `users`.`username`, `annonces`.`posted_by` FROM `username` JOIN `posted_by` ON (`username`.`id` = `annonces`.`posted_by`) WHERE `username`.`od` = 'annonces.posted_by')) ] ~ MODPATH\database\classes\Kohana\Database\MySQL.php [ 194 ] in C:\wamp\www\FreeAds\modules\database\classes\Kohana\Database\Query.php:251
2013-10-24 22:36:59 --- DEBUG: #0 C:\wamp\www\FreeAds\modules\database\classes\Kohana\Database\Query.php(251): Kohana_Database_MySQL->query(2, 'INSERT INTO `an...', false, Array)
#1 C:\wamp\www\FreeAds\modules\orm\classes\Kohana\ORM.php(1324): Kohana_Database_Query->execute(Object(Database_MySQL))
#2 C:\wamp\www\FreeAds\modules\orm\classes\Kohana\ORM.php(1421): Kohana_ORM->create(NULL)
#3 C:\wamp\www\FreeAds\application\classes\Controller\annonces.php(53): Kohana_ORM->save()
#4 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(84): Controller_Annonces->action_add()
#5 [internal function]: Kohana_Controller->execute()
#6 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Annonces))
#7 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#8 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#9 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#10 {main} in C:\wamp\www\FreeAds\modules\database\classes\Kohana\Database\Query.php:251
2013-10-24 22:43:33 --- CRITICAL: Database_Exception [ 1054 ]: Unknown column 'username.id' in 'where clause' [ INSERT INTO `annonces` (`titre`, `content`, `prix`, `region`, `categorie`, `posted_by`) VALUES ('Lololo', 'lolololll', '133', '03 - Allier', 'Autres', (SELECT * FROM `users` JOIN `annonces` ON (`username`.`id` = `annonces`.`posted_by`) WHERE `username`.`id` = 'annonces.posted_by')) ] ~ MODPATH\database\classes\Kohana\Database\MySQL.php [ 194 ] in C:\wamp\www\FreeAds\modules\database\classes\Kohana\Database\Query.php:251
2013-10-24 22:43:33 --- DEBUG: #0 C:\wamp\www\FreeAds\modules\database\classes\Kohana\Database\Query.php(251): Kohana_Database_MySQL->query(2, 'INSERT INTO `an...', false, Array)
#1 C:\wamp\www\FreeAds\modules\orm\classes\Kohana\ORM.php(1324): Kohana_Database_Query->execute(Object(Database_MySQL))
#2 C:\wamp\www\FreeAds\modules\orm\classes\Kohana\ORM.php(1421): Kohana_ORM->create(NULL)
#3 C:\wamp\www\FreeAds\application\classes\Controller\annonces.php(53): Kohana_ORM->save()
#4 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(84): Controller_Annonces->action_add()
#5 [internal function]: Kohana_Controller->execute()
#6 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Annonces))
#7 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#8 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#9 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#10 {main} in C:\wamp\www\FreeAds\modules\database\classes\Kohana\Database\Query.php:251
2013-10-24 22:46:55 --- CRITICAL: ErrorException [ 4096 ]: Object of class Database_MySQL_Result could not be converted to string ~ MODPATH\database\classes\Kohana\Database.php [ 461 ] in C:\wamp\www\FreeAds\modules\database\classes\Kohana\Database.php:461
2013-10-24 22:46:55 --- DEBUG: #0 C:\wamp\www\FreeAds\modules\database\classes\Kohana\Database.php(461): Kohana_Core::error_handler(4096, 'Object of class...', 'C:\wamp\www\Fre...', 461, Array)
#1 C:\wamp\www\FreeAds\modules\database\classes\Kohana\Database\Query\Builder\Insert.php(146): Kohana_Database->quote(Object(Database_MySQL_Result))
#2 C:\wamp\www\FreeAds\modules\database\classes\Kohana\Database\Query.php(234): Kohana_Database_Query_Builder_Insert->compile(Object(Database_MySQL))
#3 C:\wamp\www\FreeAds\modules\orm\classes\Kohana\ORM.php(1324): Kohana_Database_Query->execute(Object(Database_MySQL))
#4 C:\wamp\www\FreeAds\modules\orm\classes\Kohana\ORM.php(1421): Kohana_ORM->create(NULL)
#5 C:\wamp\www\FreeAds\application\classes\Controller\annonces.php(54): Kohana_ORM->save()
#6 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(84): Controller_Annonces->action_add()
#7 [internal function]: Kohana_Controller->execute()
#8 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Annonces))
#9 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#10 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#11 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#12 {main} in C:\wamp\www\FreeAds\modules\database\classes\Kohana\Database.php:461
2013-10-24 22:54:29 --- CRITICAL: Kohana_Exception [ 0 ]: The username property does not exist in the Model_Annonce class ~ MODPATH\orm\classes\Kohana\ORM.php [ 687 ] in C:\wamp\www\FreeAds\modules\orm\classes\Kohana\ORM.php:603
2013-10-24 22:54:29 --- DEBUG: #0 C:\wamp\www\FreeAds\modules\orm\classes\Kohana\ORM.php(603): Kohana_ORM->get('username')
#1 C:\wamp\www\FreeAds\application\views\pages\annonceslist.php(22): Kohana_ORM->__get('username')
#2 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#3 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#4 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(228): Kohana_View->render()
#5 C:\wamp\www\FreeAds\application\views\template.php(136): Kohana_View->__toString()
#6 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#7 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#8 C:\wamp\www\FreeAds\system\classes\Kohana\Controller\Template.php(44): Kohana_View->render()
#9 C:\wamp\www\FreeAds\application\classes\Controller\demo.php(50): Kohana_Controller_Template->after()
#10 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(87): Controller_Demo->after()
#11 [internal function]: Kohana_Controller->execute()
#12 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Annonces))
#13 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#14 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#15 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#16 {main} in C:\wamp\www\FreeAds\modules\orm\classes\Kohana\ORM.php:603
2013-10-24 22:55:44 --- CRITICAL: Kohana_Exception [ 0 ]: The username property does not exist in the Model_Annonce class ~ MODPATH\orm\classes\Kohana\ORM.php [ 687 ] in C:\wamp\www\FreeAds\modules\orm\classes\Kohana\ORM.php:603
2013-10-24 22:55:44 --- DEBUG: #0 C:\wamp\www\FreeAds\modules\orm\classes\Kohana\ORM.php(603): Kohana_ORM->get('username')
#1 C:\wamp\www\FreeAds\application\views\pages\annonceslist.php(22): Kohana_ORM->__get('username')
#2 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#3 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#4 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(228): Kohana_View->render()
#5 C:\wamp\www\FreeAds\application\views\template.php(136): Kohana_View->__toString()
#6 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#7 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#8 C:\wamp\www\FreeAds\system\classes\Kohana\Controller\Template.php(44): Kohana_View->render()
#9 C:\wamp\www\FreeAds\application\classes\Controller\demo.php(50): Kohana_Controller_Template->after()
#10 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(87): Controller_Demo->after()
#11 [internal function]: Kohana_Controller->execute()
#12 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Annonces))
#13 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#14 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#15 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#16 {main} in C:\wamp\www\FreeAds\modules\orm\classes\Kohana\ORM.php:603
2013-10-24 22:57:22 --- CRITICAL: Kohana_Exception [ 0 ]: The username property does not exist in the Model_Annonce class ~ MODPATH\orm\classes\Kohana\ORM.php [ 687 ] in C:\wamp\www\FreeAds\modules\orm\classes\Kohana\ORM.php:603
2013-10-24 22:57:22 --- DEBUG: #0 C:\wamp\www\FreeAds\modules\orm\classes\Kohana\ORM.php(603): Kohana_ORM->get('username')
#1 C:\wamp\www\FreeAds\application\views\pages\annonceslist.php(22): Kohana_ORM->__get('username')
#2 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#3 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#4 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(228): Kohana_View->render()
#5 C:\wamp\www\FreeAds\application\views\template.php(136): Kohana_View->__toString()
#6 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#7 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#8 C:\wamp\www\FreeAds\system\classes\Kohana\Controller\Template.php(44): Kohana_View->render()
#9 C:\wamp\www\FreeAds\application\classes\Controller\demo.php(50): Kohana_Controller_Template->after()
#10 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(87): Controller_Demo->after()
#11 [internal function]: Kohana_Controller->execute()
#12 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Annonces))
#13 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#14 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#15 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#16 {main} in C:\wamp\www\FreeAds\modules\orm\classes\Kohana\ORM.php:603
2013-10-24 23:06:06 --- CRITICAL: ErrorException [ 8 ]: Trying to get property of non-object ~ APPPATH\views\pages\annonceslist.php [ 17 ] in C:\wamp\www\FreeAds\application\views\pages\annonceslist.php:17
2013-10-24 23:06:06 --- DEBUG: #0 C:\wamp\www\FreeAds\application\views\pages\annonceslist.php(17): Kohana_Core::error_handler(8, 'Trying to get p...', 'C:\wamp\www\Fre...', 17, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#2 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#3 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(228): Kohana_View->render()
#4 C:\wamp\www\FreeAds\application\views\template.php(136): Kohana_View->__toString()
#5 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#6 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#7 C:\wamp\www\FreeAds\system\classes\Kohana\Controller\Template.php(44): Kohana_View->render()
#8 C:\wamp\www\FreeAds\application\classes\Controller\demo.php(50): Kohana_Controller_Template->after()
#9 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(87): Controller_Demo->after()
#10 [internal function]: Kohana_Controller->execute()
#11 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Annonces))
#12 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#13 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#14 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#15 {main} in C:\wamp\www\FreeAds\application\views\pages\annonceslist.php:17
2013-10-24 23:13:02 --- CRITICAL: ErrorException [ 8 ]: Undefined variable: list ~ APPPATH\classes\Controller\annonces.php [ 17 ] in C:\wamp\www\FreeAds\application\classes\Controller\annonces.php:17
2013-10-24 23:13:02 --- DEBUG: #0 C:\wamp\www\FreeAds\application\classes\Controller\annonces.php(17): Kohana_Core::error_handler(8, 'Undefined varia...', 'C:\wamp\www\Fre...', 17, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(84): Controller_Annonces->action_list()
#2 [internal function]: Kohana_Controller->execute()
#3 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Annonces))
#4 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#5 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#6 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#7 {main} in C:\wamp\www\FreeAds\application\classes\Controller\annonces.php:17
2013-10-24 23:42:07 --- CRITICAL: ErrorException [ 1 ]: Call to undefined method HTML::email() ~ APPPATH\views\pages\annonceslist.php [ 24 ] in file:line
2013-10-24 23:42:07 --- DEBUG: #0 [internal function]: Kohana_Core::shutdown_handler()
#1 {main} in file:line