<?php defined('SYSPATH') OR die('No direct script access.'); ?>

2013-10-22 10:28:25 --- CRITICAL: ErrorException [ 4 ]: syntax error, unexpected '{', expecting '(' ~ APPPATH\classes\Controller\users.php [ 33 ] in file:line
2013-10-22 10:28:25 --- DEBUG: #0 [internal function]: Kohana_Core::shutdown_handler()
#1 {main} in file:line
2013-10-22 10:28:55 --- CRITICAL: ORM_Validation_Exception [ 0 ]: Failed to validate array ~ MODPATH\orm\classes\Kohana\ORM.php [ 1275 ] in C:\wamp\www\FreeAds\modules\orm\classes\Kohana\ORM.php:1302
2013-10-22 10:28:55 --- DEBUG: #0 C:\wamp\www\FreeAds\modules\orm\classes\Kohana\ORM.php(1302): Kohana_ORM->check(Object(Validation))
#1 C:\wamp\www\FreeAds\modules\orm\classes\Model\Auth\User.php(167): Kohana_ORM->create(Object(Validation))
#2 C:\wamp\www\FreeAds\application\classes\Controller\users.php(27): Model_Auth_User->create_user(Array, Array)
#3 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(84): Controller_Users->action_register()
#4 [internal function]: Kohana_Controller->execute()
#5 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Users))
#6 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#7 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#8 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#9 {main} in C:\wamp\www\FreeAds\modules\orm\classes\Kohana\ORM.php:1302
2013-10-22 10:29:54 --- CRITICAL: ORM_Validation_Exception [ 0 ]: Failed to validate array ~ MODPATH\orm\classes\Kohana\ORM.php [ 1275 ] in C:\wamp\www\FreeAds\modules\orm\classes\Kohana\ORM.php:1302
2013-10-22 10:29:54 --- DEBUG: #0 C:\wamp\www\FreeAds\modules\orm\classes\Kohana\ORM.php(1302): Kohana_ORM->check(Object(Validation))
#1 C:\wamp\www\FreeAds\modules\orm\classes\Model\Auth\User.php(167): Kohana_ORM->create(Object(Validation))
#2 C:\wamp\www\FreeAds\application\classes\Controller\users.php(27): Model_Auth_User->create_user(Array, Array)
#3 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(84): Controller_Users->action_register()
#4 [internal function]: Kohana_Controller->execute()
#5 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Users))
#6 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#7 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#8 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#9 {main} in C:\wamp\www\FreeAds\modules\orm\classes\Kohana\ORM.php:1302
2013-10-22 10:46:30 --- CRITICAL: ORM_Validation_Exception [ 0 ]: Failed to validate array ~ MODPATH\orm\classes\Kohana\ORM.php [ 1275 ] in C:\wamp\www\FreeAds\modules\orm\classes\Kohana\ORM.php:1302
2013-10-22 10:46:30 --- DEBUG: #0 C:\wamp\www\FreeAds\modules\orm\classes\Kohana\ORM.php(1302): Kohana_ORM->check(Object(Validation))
#1 C:\wamp\www\FreeAds\modules\orm\classes\Model\Auth\User.php(167): Kohana_ORM->create(Object(Validation))
#2 C:\wamp\www\FreeAds\application\classes\Controller\users.php(22): Model_Auth_User->create_user(Array, Array)
#3 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(84): Controller_Users->action_register()
#4 [internal function]: Kohana_Controller->execute()
#5 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Users))
#6 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#7 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#8 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#9 {main} in C:\wamp\www\FreeAds\modules\orm\classes\Kohana\ORM.php:1302
2013-10-22 10:46:37 --- CRITICAL: ErrorException [ 8 ]: Undefined variable: message ~ APPPATH\views\template.php [ 111 ] in C:\wamp\www\FreeAds\application\views\template.php:111
2013-10-22 10:46:37 --- DEBUG: #0 C:\wamp\www\FreeAds\application\views\template.php(111): Kohana_Core::error_handler(8, 'Undefined varia...', 'C:\wamp\www\Fre...', 111, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#2 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#3 C:\wamp\www\FreeAds\system\classes\Kohana\Controller\Template.php(44): Kohana_View->render()
#4 C:\wamp\www\FreeAds\application\classes\Controller\demo.php(51): Kohana_Controller_Template->after()
#5 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(87): Controller_Demo->after()
#6 [internal function]: Kohana_Controller->execute()
#7 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Users))
#8 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#9 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#10 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#11 {main} in C:\wamp\www\FreeAds\application\views\template.php:111
2013-10-22 10:46:49 --- CRITICAL: ErrorException [ 8 ]: Undefined variable: errors ~ APPPATH\views\template.php [ 112 ] in C:\wamp\www\FreeAds\application\views\template.php:112
2013-10-22 10:46:49 --- DEBUG: #0 C:\wamp\www\FreeAds\application\views\template.php(112): Kohana_Core::error_handler(8, 'Undefined varia...', 'C:\wamp\www\Fre...', 112, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#2 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#3 C:\wamp\www\FreeAds\system\classes\Kohana\Controller\Template.php(44): Kohana_View->render()
#4 C:\wamp\www\FreeAds\application\classes\Controller\demo.php(51): Kohana_Controller_Template->after()
#5 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(87): Controller_Demo->after()
#6 [internal function]: Kohana_Controller->execute()
#7 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Users))
#8 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#9 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#10 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#11 {main} in C:\wamp\www\FreeAds\application\views\template.php:112
2013-10-22 10:47:13 --- CRITICAL: ErrorException [ 8 ]: Undefined variable: errors ~ APPPATH\views\template.php [ 112 ] in C:\wamp\www\FreeAds\application\views\template.php:112
2013-10-22 10:47:13 --- DEBUG: #0 C:\wamp\www\FreeAds\application\views\template.php(112): Kohana_Core::error_handler(8, 'Undefined varia...', 'C:\wamp\www\Fre...', 112, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#2 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#3 C:\wamp\www\FreeAds\system\classes\Kohana\Controller\Template.php(44): Kohana_View->render()
#4 C:\wamp\www\FreeAds\application\classes\Controller\demo.php(51): Kohana_Controller_Template->after()
#5 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(87): Controller_Demo->after()
#6 [internal function]: Kohana_Controller->execute()
#7 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Users))
#8 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#9 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#10 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#11 {main} in C:\wamp\www\FreeAds\application\views\template.php:112
2013-10-22 10:47:17 --- CRITICAL: ErrorException [ 8 ]: Undefined variable: errors ~ APPPATH\views\template.php [ 112 ] in C:\wamp\www\FreeAds\application\views\template.php:112
2013-10-22 10:47:17 --- DEBUG: #0 C:\wamp\www\FreeAds\application\views\template.php(112): Kohana_Core::error_handler(8, 'Undefined varia...', 'C:\wamp\www\Fre...', 112, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#2 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#3 C:\wamp\www\FreeAds\system\classes\Kohana\Controller\Template.php(44): Kohana_View->render()
#4 C:\wamp\www\FreeAds\application\classes\Controller\demo.php(51): Kohana_Controller_Template->after()
#5 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(87): Controller_Demo->after()
#6 [internal function]: Kohana_Controller->execute()
#7 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Users))
#8 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#9 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#10 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#11 {main} in C:\wamp\www\FreeAds\application\views\template.php:112
2013-10-22 10:47:40 --- CRITICAL: ErrorException [ 8 ]: Undefined variable: message ~ APPPATH\views\template.php [ 111 ] in C:\wamp\www\FreeAds\application\views\template.php:111
2013-10-22 10:47:40 --- DEBUG: #0 C:\wamp\www\FreeAds\application\views\template.php(111): Kohana_Core::error_handler(8, 'Undefined varia...', 'C:\wamp\www\Fre...', 111, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#2 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#3 C:\wamp\www\FreeAds\system\classes\Kohana\Controller\Template.php(44): Kohana_View->render()
#4 C:\wamp\www\FreeAds\application\classes\Controller\demo.php(51): Kohana_Controller_Template->after()
#5 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(87): Controller_Demo->after()
#6 [internal function]: Kohana_Controller->execute()
#7 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Users))
#8 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#9 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#10 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#11 {main} in C:\wamp\www\FreeAds\application\views\template.php:111
2013-10-22 10:48:27 --- CRITICAL: ORM_Validation_Exception [ 0 ]: Failed to validate array ~ MODPATH\orm\classes\Kohana\ORM.php [ 1275 ] in C:\wamp\www\FreeAds\modules\orm\classes\Kohana\ORM.php:1302
2013-10-22 10:48:27 --- DEBUG: #0 C:\wamp\www\FreeAds\modules\orm\classes\Kohana\ORM.php(1302): Kohana_ORM->check(Object(Validation))
#1 C:\wamp\www\FreeAds\modules\orm\classes\Model\Auth\User.php(167): Kohana_ORM->create(Object(Validation))
#2 C:\wamp\www\FreeAds\application\classes\Controller\users.php(22): Model_Auth_User->create_user(Array, Array)
#3 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(84): Controller_Users->action_register()
#4 [internal function]: Kohana_Controller->execute()
#5 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Users))
#6 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#7 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#8 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#9 {main} in C:\wamp\www\FreeAds\modules\orm\classes\Kohana\ORM.php:1302
2013-10-22 10:56:11 --- CRITICAL: View_Exception [ 0 ]: The requested view users/register could not be found ~ SYSPATH\classes\Kohana\View.php [ 257 ] in C:\wamp\www\FreeAds\system\classes\Kohana\View.php:137
2013-10-22 10:56:11 --- DEBUG: #0 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(137): Kohana_View->set_filename('users/register')
#1 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(30): Kohana_View->__construct('users/register', NULL)
#2 C:\wamp\www\FreeAds\application\classes\Controller\users.php(12): Kohana_View::factory('users/register')
#3 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(84): Controller_Users->action_register()
#4 [internal function]: Kohana_Controller->execute()
#5 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Users))
#6 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#7 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#8 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#9 {main} in C:\wamp\www\FreeAds\system\classes\Kohana\View.php:137
2013-10-22 10:56:52 --- CRITICAL: View_Exception [ 0 ]: The requested view users/register could not be found ~ SYSPATH\classes\Kohana\View.php [ 257 ] in C:\wamp\www\FreeAds\system\classes\Kohana\View.php:137
2013-10-22 10:56:52 --- DEBUG: #0 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(137): Kohana_View->set_filename('users/register')
#1 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(30): Kohana_View->__construct('users/register', NULL)
#2 C:\wamp\www\FreeAds\application\classes\Controller\users.php(12): Kohana_View::factory('users/register')
#3 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(84): Controller_Users->action_register()
#4 [internal function]: Kohana_Controller->execute()
#5 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Users))
#6 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#7 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#8 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#9 {main} in C:\wamp\www\FreeAds\system\classes\Kohana\View.php:137
2013-10-22 10:59:21 --- CRITICAL: ErrorException [ 8 ]: Undefined variable: styles ~ APPPATH\views\template.php [ 8 ] in C:\wamp\www\FreeAds\application\views\template.php:8
2013-10-22 10:59:21 --- DEBUG: #0 C:\wamp\www\FreeAds\application\views\template.php(8): Kohana_Core::error_handler(8, 'Undefined varia...', 'C:\wamp\www\Fre...', 8, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#2 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#3 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(228): Kohana_View->render()
#4 C:\wamp\www\FreeAds\application\views\template.php(115): Kohana_View->__toString()
#5 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#6 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#7 C:\wamp\www\FreeAds\system\classes\Kohana\Controller\Template.php(44): Kohana_View->render()
#8 C:\wamp\www\FreeAds\application\classes\Controller\demo.php(51): Kohana_Controller_Template->after()
#9 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(87): Controller_Demo->after()
#10 [internal function]: Kohana_Controller->execute()
#11 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Users))
#12 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#13 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#14 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#15 {main} in C:\wamp\www\FreeAds\application\views\template.php:8
2013-10-22 11:08:03 --- CRITICAL: ErrorException [ 8 ]: Undefined variable: bite ~ APPPATH\views\pages\home.php [ 2 ] in C:\wamp\www\FreeAds\application\views\pages\home.php:2
2013-10-22 11:08:03 --- DEBUG: #0 C:\wamp\www\FreeAds\application\views\pages\home.php(2): Kohana_Core::error_handler(8, 'Undefined varia...', 'C:\wamp\www\Fre...', 2, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#2 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#3 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(228): Kohana_View->render()
#4 C:\wamp\www\FreeAds\application\views\template.php(115): Kohana_View->__toString()
#5 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#6 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#7 C:\wamp\www\FreeAds\system\classes\Kohana\Controller\Template.php(44): Kohana_View->render()
#8 C:\wamp\www\FreeAds\application\classes\Controller\demo.php(51): Kohana_Controller_Template->after()
#9 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(87): Controller_Demo->after()
#10 [internal function]: Kohana_Controller->execute()
#11 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Users))
#12 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#13 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#14 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#15 {main} in C:\wamp\www\FreeAds\application\views\pages\home.php:2
2013-10-22 11:08:18 --- CRITICAL: ErrorException [ 8 ]: Undefined variable: bite ~ APPPATH\views\pages\home.php [ 2 ] in C:\wamp\www\FreeAds\application\views\pages\home.php:2
2013-10-22 11:08:18 --- DEBUG: #0 C:\wamp\www\FreeAds\application\views\pages\home.php(2): Kohana_Core::error_handler(8, 'Undefined varia...', 'C:\wamp\www\Fre...', 2, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#2 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#3 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(228): Kohana_View->render()
#4 C:\wamp\www\FreeAds\application\views\template.php(115): Kohana_View->__toString()
#5 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#6 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#7 C:\wamp\www\FreeAds\system\classes\Kohana\Controller\Template.php(44): Kohana_View->render()
#8 C:\wamp\www\FreeAds\application\classes\Controller\demo.php(51): Kohana_Controller_Template->after()
#9 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(87): Controller_Demo->after()
#10 [internal function]: Kohana_Controller->execute()
#11 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Users))
#12 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#13 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#14 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#15 {main} in C:\wamp\www\FreeAds\application\views\pages\home.php:2
2013-10-22 11:10:05 --- CRITICAL: ErrorException [ 1 ]: Cannot pass parameter 2 by reference ~ APPPATH\classes\Controller\users.php [ 16 ] in file:line
2013-10-22 11:10:05 --- DEBUG: #0 [internal function]: Kohana_Core::shutdown_handler()
#1 {main} in file:line
2013-10-22 11:10:43 --- CRITICAL: ErrorException [ 1 ]: Cannot pass parameter 2 by reference ~ APPPATH\classes\Controller\users.php [ 16 ] in file:line
2013-10-22 11:10:43 --- DEBUG: #0 [internal function]: Kohana_Core::shutdown_handler()
#1 {main} in file:line
2013-10-22 11:11:23 --- CRITICAL: ErrorException [ 8 ]: Undefined variable: bite ~ APPPATH\views\pages\home.php [ 2 ] in C:\wamp\www\FreeAds\application\views\pages\home.php:2
2013-10-22 11:11:23 --- DEBUG: #0 C:\wamp\www\FreeAds\application\views\pages\home.php(2): Kohana_Core::error_handler(8, 'Undefined varia...', 'C:\wamp\www\Fre...', 2, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#2 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#3 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(228): Kohana_View->render()
#4 C:\wamp\www\FreeAds\application\views\template.php(115): Kohana_View->__toString()
#5 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#6 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#7 C:\wamp\www\FreeAds\system\classes\Kohana\Controller\Template.php(44): Kohana_View->render()
#8 C:\wamp\www\FreeAds\application\classes\Controller\demo.php(51): Kohana_Controller_Template->after()
#9 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(87): Controller_Demo->after()
#10 [internal function]: Kohana_Controller->execute()
#11 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Users))
#12 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#13 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#14 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#15 {main} in C:\wamp\www\FreeAds\application\views\pages\home.php:2
2013-10-22 11:12:02 --- CRITICAL: ErrorException [ 8 ]: Undefined variable: bite ~ APPPATH\views\pages\home.php [ 2 ] in C:\wamp\www\FreeAds\application\views\pages\home.php:2
2013-10-22 11:12:02 --- DEBUG: #0 C:\wamp\www\FreeAds\application\views\pages\home.php(2): Kohana_Core::error_handler(8, 'Undefined varia...', 'C:\wamp\www\Fre...', 2, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#2 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#3 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(228): Kohana_View->render()
#4 C:\wamp\www\FreeAds\application\views\template.php(115): Kohana_View->__toString()
#5 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#6 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#7 C:\wamp\www\FreeAds\system\classes\Kohana\Controller\Template.php(44): Kohana_View->render()
#8 C:\wamp\www\FreeAds\application\classes\Controller\demo.php(51): Kohana_Controller_Template->after()
#9 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(87): Controller_Demo->after()
#10 [internal function]: Kohana_Controller->execute()
#11 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Users))
#12 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#13 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#14 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#15 {main} in C:\wamp\www\FreeAds\application\views\pages\home.php:2
2013-10-22 11:13:12 --- CRITICAL: ErrorException [ 8 ]: Undefined variable: bite ~ APPPATH\views\pages\home.php [ 2 ] in C:\wamp\www\FreeAds\application\views\pages\home.php:2
2013-10-22 11:13:12 --- DEBUG: #0 C:\wamp\www\FreeAds\application\views\pages\home.php(2): Kohana_Core::error_handler(8, 'Undefined varia...', 'C:\wamp\www\Fre...', 2, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#2 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#3 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(228): Kohana_View->render()
#4 C:\wamp\www\FreeAds\application\views\template.php(115): Kohana_View->__toString()
#5 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#6 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#7 C:\wamp\www\FreeAds\system\classes\Kohana\Controller\Template.php(44): Kohana_View->render()
#8 C:\wamp\www\FreeAds\application\classes\Controller\demo.php(51): Kohana_Controller_Template->after()
#9 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(87): Controller_Demo->after()
#10 [internal function]: Kohana_Controller->execute()
#11 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Users))
#12 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#13 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#14 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#15 {main} in C:\wamp\www\FreeAds\application\views\pages\home.php:2
2013-10-22 11:14:44 --- CRITICAL: ErrorException [ 8 ]: Undefined variable: bite ~ APPPATH\views\pages\home.php [ 2 ] in C:\wamp\www\FreeAds\application\views\pages\home.php:2
2013-10-22 11:14:44 --- DEBUG: #0 C:\wamp\www\FreeAds\application\views\pages\home.php(2): Kohana_Core::error_handler(8, 'Undefined varia...', 'C:\wamp\www\Fre...', 2, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#2 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#3 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(228): Kohana_View->render()
#4 C:\wamp\www\FreeAds\application\views\template.php(115): Kohana_View->__toString()
#5 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#6 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#7 C:\wamp\www\FreeAds\system\classes\Kohana\Controller\Template.php(44): Kohana_View->render()
#8 C:\wamp\www\FreeAds\application\classes\Controller\demo.php(51): Kohana_Controller_Template->after()
#9 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(87): Controller_Demo->after()
#10 [internal function]: Kohana_Controller->execute()
#11 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Users))
#12 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#13 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#14 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#15 {main} in C:\wamp\www\FreeAds\application\views\pages\home.php:2
2013-10-22 11:36:20 --- CRITICAL: ErrorException [ 4 ]: syntax error, unexpected 'echo' (T_ECHO) ~ APPPATH\views\pages\home.php [ 3 ] in file:line
2013-10-22 11:36:20 --- DEBUG: #0 [internal function]: Kohana_Core::shutdown_handler()
#1 {main} in file:line
2013-10-22 11:37:15 --- CRITICAL: ErrorException [ 4 ]: syntax error, unexpected 'echo' (T_ECHO) ~ APPPATH\views\pages\home.php [ 3 ] in file:line
2013-10-22 11:37:15 --- DEBUG: #0 [internal function]: Kohana_Core::shutdown_handler()
#1 {main} in file:line
2013-10-22 18:05:34 --- CRITICAL: ErrorException [ 4 ]: syntax error, unexpected 'else' (T_ELSE) ~ APPPATH\views\template.php [ 28 ] in file:line
2013-10-22 18:05:34 --- DEBUG: #0 [internal function]: Kohana_Core::shutdown_handler()
#1 {main} in file:line
2013-10-22 19:16:14 --- CRITICAL: ErrorException [ 1 ]: Call to undefined method Controller_Users::isset_session() ~ APPPATH\views\template.php [ 26 ] in file:line
2013-10-22 19:16:14 --- DEBUG: #0 [internal function]: Kohana_Core::shutdown_handler()
#1 {main} in file:line
2013-10-22 19:21:27 --- CRITICAL: ErrorException [ 8 ]: Undefined variable: users ~ APPPATH\views\pages\updateprofil.php [ 5 ] in C:\wamp\www\FreeAds\application\views\pages\updateprofil.php:5
2013-10-22 19:21:27 --- DEBUG: #0 C:\wamp\www\FreeAds\application\views\pages\updateprofil.php(5): Kohana_Core::error_handler(8, 'Undefined varia...', 'C:\wamp\www\Fre...', 5, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#2 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#3 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(228): Kohana_View->render()
#4 C:\wamp\www\FreeAds\application\views\template.php(130): Kohana_View->__toString()
#5 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#6 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#7 C:\wamp\www\FreeAds\system\classes\Kohana\Controller\Template.php(44): Kohana_View->render()
#8 C:\wamp\www\FreeAds\application\classes\Controller\demo.php(51): Kohana_Controller_Template->after()
#9 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(87): Controller_Demo->after()
#10 [internal function]: Kohana_Controller->execute()
#11 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Users))
#12 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#13 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#14 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#15 {main} in C:\wamp\www\FreeAds\application\views\pages\updateprofil.php:5
2013-10-22 19:22:09 --- CRITICAL: ErrorException [ 8 ]: Undefined variable: users ~ APPPATH\views\pages\updateprofil.php [ 5 ] in C:\wamp\www\FreeAds\application\views\pages\updateprofil.php:5
2013-10-22 19:22:09 --- DEBUG: #0 C:\wamp\www\FreeAds\application\views\pages\updateprofil.php(5): Kohana_Core::error_handler(8, 'Undefined varia...', 'C:\wamp\www\Fre...', 5, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#2 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#3 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(228): Kohana_View->render()
#4 C:\wamp\www\FreeAds\application\views\template.php(130): Kohana_View->__toString()
#5 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#6 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#7 C:\wamp\www\FreeAds\system\classes\Kohana\Controller\Template.php(44): Kohana_View->render()
#8 C:\wamp\www\FreeAds\application\classes\Controller\demo.php(51): Kohana_Controller_Template->after()
#9 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(87): Controller_Demo->after()
#10 [internal function]: Kohana_Controller->execute()
#11 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Users))
#12 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#13 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#14 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#15 {main} in C:\wamp\www\FreeAds\application\views\pages\updateprofil.php:5
2013-10-22 19:22:11 --- CRITICAL: ErrorException [ 8 ]: Undefined variable: users ~ APPPATH\views\pages\updateprofil.php [ 5 ] in C:\wamp\www\FreeAds\application\views\pages\updateprofil.php:5
2013-10-22 19:22:11 --- DEBUG: #0 C:\wamp\www\FreeAds\application\views\pages\updateprofil.php(5): Kohana_Core::error_handler(8, 'Undefined varia...', 'C:\wamp\www\Fre...', 5, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#2 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#3 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(228): Kohana_View->render()
#4 C:\wamp\www\FreeAds\application\views\template.php(130): Kohana_View->__toString()
#5 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#6 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#7 C:\wamp\www\FreeAds\system\classes\Kohana\Controller\Template.php(44): Kohana_View->render()
#8 C:\wamp\www\FreeAds\application\classes\Controller\demo.php(51): Kohana_Controller_Template->after()
#9 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(87): Controller_Demo->after()
#10 [internal function]: Kohana_Controller->execute()
#11 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Users))
#12 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#13 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#14 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#15 {main} in C:\wamp\www\FreeAds\application\views\pages\updateprofil.php:5
2013-10-22 19:22:16 --- CRITICAL: ErrorException [ 8 ]: Undefined variable: users ~ APPPATH\views\pages\updateprofil.php [ 5 ] in C:\wamp\www\FreeAds\application\views\pages\updateprofil.php:5
2013-10-22 19:22:16 --- DEBUG: #0 C:\wamp\www\FreeAds\application\views\pages\updateprofil.php(5): Kohana_Core::error_handler(8, 'Undefined varia...', 'C:\wamp\www\Fre...', 5, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#2 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#3 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(228): Kohana_View->render()
#4 C:\wamp\www\FreeAds\application\views\template.php(130): Kohana_View->__toString()
#5 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#6 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#7 C:\wamp\www\FreeAds\system\classes\Kohana\Controller\Template.php(44): Kohana_View->render()
#8 C:\wamp\www\FreeAds\application\classes\Controller\demo.php(51): Kohana_Controller_Template->after()
#9 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(87): Controller_Demo->after()
#10 [internal function]: Kohana_Controller->execute()
#11 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Users))
#12 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#13 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#14 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#15 {main} in C:\wamp\www\FreeAds\application\views\pages\updateprofil.php:5
2013-10-22 19:23:02 --- CRITICAL: ErrorException [ 8 ]: Undefined variable: users ~ APPPATH\views\pages\updateprofil.php [ 5 ] in C:\wamp\www\FreeAds\application\views\pages\updateprofil.php:5
2013-10-22 19:23:02 --- DEBUG: #0 C:\wamp\www\FreeAds\application\views\pages\updateprofil.php(5): Kohana_Core::error_handler(8, 'Undefined varia...', 'C:\wamp\www\Fre...', 5, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#2 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#3 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(228): Kohana_View->render()
#4 C:\wamp\www\FreeAds\application\views\template.php(130): Kohana_View->__toString()
#5 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#6 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#7 C:\wamp\www\FreeAds\system\classes\Kohana\Controller\Template.php(44): Kohana_View->render()
#8 C:\wamp\www\FreeAds\application\classes\Controller\demo.php(51): Kohana_Controller_Template->after()
#9 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(87): Controller_Demo->after()
#10 [internal function]: Kohana_Controller->execute()
#11 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Users))
#12 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#13 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#14 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#15 {main} in C:\wamp\www\FreeAds\application\views\pages\updateprofil.php:5
2013-10-22 19:31:08 --- CRITICAL: ErrorException [ 8 ]: Undefined variable: users ~ APPPATH\views\pages\updateprofil.php [ 5 ] in C:\wamp\www\FreeAds\application\views\pages\updateprofil.php:5
2013-10-22 19:31:08 --- DEBUG: #0 C:\wamp\www\FreeAds\application\views\pages\updateprofil.php(5): Kohana_Core::error_handler(8, 'Undefined varia...', 'C:\wamp\www\Fre...', 5, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#2 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#3 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(228): Kohana_View->render()
#4 C:\wamp\www\FreeAds\application\views\template.php(130): Kohana_View->__toString()
#5 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#6 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#7 C:\wamp\www\FreeAds\system\classes\Kohana\Controller\Template.php(44): Kohana_View->render()
#8 C:\wamp\www\FreeAds\application\classes\Controller\demo.php(51): Kohana_Controller_Template->after()
#9 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(87): Controller_Demo->after()
#10 [internal function]: Kohana_Controller->execute()
#11 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Users))
#12 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#13 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#14 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#15 {main} in C:\wamp\www\FreeAds\application\views\pages\updateprofil.php:5
2013-10-22 19:31:19 --- CRITICAL: ErrorException [ 8 ]: Undefined variable: users ~ APPPATH\views\pages\updateprofil.php [ 5 ] in C:\wamp\www\FreeAds\application\views\pages\updateprofil.php:5
2013-10-22 19:31:19 --- DEBUG: #0 C:\wamp\www\FreeAds\application\views\pages\updateprofil.php(5): Kohana_Core::error_handler(8, 'Undefined varia...', 'C:\wamp\www\Fre...', 5, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#2 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#3 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(228): Kohana_View->render()
#4 C:\wamp\www\FreeAds\application\views\template.php(130): Kohana_View->__toString()
#5 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#6 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#7 C:\wamp\www\FreeAds\system\classes\Kohana\Controller\Template.php(44): Kohana_View->render()
#8 C:\wamp\www\FreeAds\application\classes\Controller\demo.php(51): Kohana_Controller_Template->after()
#9 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(87): Controller_Demo->after()
#10 [internal function]: Kohana_Controller->execute()
#11 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Users))
#12 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#13 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#14 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#15 {main} in C:\wamp\www\FreeAds\application\views\pages\updateprofil.php:5
2013-10-22 19:31:37 --- CRITICAL: ErrorException [ 8 ]: Undefined variable: users ~ APPPATH\views\pages\updateprofil.php [ 5 ] in C:\wamp\www\FreeAds\application\views\pages\updateprofil.php:5
2013-10-22 19:31:37 --- DEBUG: #0 C:\wamp\www\FreeAds\application\views\pages\updateprofil.php(5): Kohana_Core::error_handler(8, 'Undefined varia...', 'C:\wamp\www\Fre...', 5, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#2 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#3 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(228): Kohana_View->render()
#4 C:\wamp\www\FreeAds\application\views\template.php(130): Kohana_View->__toString()
#5 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#6 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#7 C:\wamp\www\FreeAds\system\classes\Kohana\Controller\Template.php(44): Kohana_View->render()
#8 C:\wamp\www\FreeAds\application\classes\Controller\demo.php(51): Kohana_Controller_Template->after()
#9 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(87): Controller_Demo->after()
#10 [internal function]: Kohana_Controller->execute()
#11 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Users))
#12 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#13 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#14 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#15 {main} in C:\wamp\www\FreeAds\application\views\pages\updateprofil.php:5
2013-10-22 19:31:43 --- CRITICAL: ErrorException [ 8 ]: Undefined variable: users ~ APPPATH\views\pages\updateprofil.php [ 5 ] in C:\wamp\www\FreeAds\application\views\pages\updateprofil.php:5
2013-10-22 19:31:43 --- DEBUG: #0 C:\wamp\www\FreeAds\application\views\pages\updateprofil.php(5): Kohana_Core::error_handler(8, 'Undefined varia...', 'C:\wamp\www\Fre...', 5, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#2 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#3 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(228): Kohana_View->render()
#4 C:\wamp\www\FreeAds\application\views\template.php(130): Kohana_View->__toString()
#5 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#6 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#7 C:\wamp\www\FreeAds\system\classes\Kohana\Controller\Template.php(44): Kohana_View->render()
#8 C:\wamp\www\FreeAds\application\classes\Controller\demo.php(51): Kohana_Controller_Template->after()
#9 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(87): Controller_Demo->after()
#10 [internal function]: Kohana_Controller->execute()
#11 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Users))
#12 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#13 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#14 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#15 {main} in C:\wamp\www\FreeAds\application\views\pages\updateprofil.php:5
2013-10-22 20:01:20 --- CRITICAL: ErrorException [ 4 ]: syntax error, unexpected 'if' (T_IF), expecting ',' or ';' ~ APPPATH\classes\Controller\users.php [ 89 ] in file:line
2013-10-22 20:01:20 --- DEBUG: #0 [internal function]: Kohana_Core::shutdown_handler()
#1 {main} in file:line
2013-10-22 20:04:48 --- CRITICAL: ErrorException [ 8 ]: Undefined variable: users ~ APPPATH\views\pages\updateprofil.php [ 5 ] in C:\wamp\www\FreeAds\application\views\pages\updateprofil.php:5
2013-10-22 20:04:48 --- DEBUG: #0 C:\wamp\www\FreeAds\application\views\pages\updateprofil.php(5): Kohana_Core::error_handler(8, 'Undefined varia...', 'C:\wamp\www\Fre...', 5, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#2 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#3 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(228): Kohana_View->render()
#4 C:\wamp\www\FreeAds\application\views\template.php(130): Kohana_View->__toString()
#5 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#6 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#7 C:\wamp\www\FreeAds\system\classes\Kohana\Controller\Template.php(44): Kohana_View->render()
#8 C:\wamp\www\FreeAds\application\classes\Controller\demo.php(51): Kohana_Controller_Template->after()
#9 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(87): Controller_Demo->after()
#10 [internal function]: Kohana_Controller->execute()
#11 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Users))
#12 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#13 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#14 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#15 {main} in C:\wamp\www\FreeAds\application\views\pages\updateprofil.php:5
2013-10-22 20:05:12 --- CRITICAL: ErrorException [ 8 ]: Undefined variable: users ~ APPPATH\views\pages\updateprofil.php [ 5 ] in C:\wamp\www\FreeAds\application\views\pages\updateprofil.php:5
2013-10-22 20:05:12 --- DEBUG: #0 C:\wamp\www\FreeAds\application\views\pages\updateprofil.php(5): Kohana_Core::error_handler(8, 'Undefined varia...', 'C:\wamp\www\Fre...', 5, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#2 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#3 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(228): Kohana_View->render()
#4 C:\wamp\www\FreeAds\application\views\template.php(130): Kohana_View->__toString()
#5 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#6 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#7 C:\wamp\www\FreeAds\system\classes\Kohana\Controller\Template.php(44): Kohana_View->render()
#8 C:\wamp\www\FreeAds\application\classes\Controller\demo.php(51): Kohana_Controller_Template->after()
#9 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(87): Controller_Demo->after()
#10 [internal function]: Kohana_Controller->execute()
#11 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Users))
#12 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#13 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#14 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#15 {main} in C:\wamp\www\FreeAds\application\views\pages\updateprofil.php:5
2013-10-22 20:06:20 --- CRITICAL: ErrorException [ 4 ]: syntax error, unexpected ',' ~ APPPATH\classes\Controller\users.php [ 112 ] in file:line
2013-10-22 20:06:20 --- DEBUG: #0 [internal function]: Kohana_Core::shutdown_handler()
#1 {main} in file:line
2013-10-22 20:14:20 --- CRITICAL: ORM_Validation_Exception [ 0 ]: Failed to validate array ~ MODPATH\orm\classes\Kohana\ORM.php [ 1275 ] in C:\wamp\www\FreeAds\modules\orm\classes\Kohana\ORM.php:1362
2013-10-22 20:14:20 --- DEBUG: #0 C:\wamp\www\FreeAds\modules\orm\classes\Kohana\ORM.php(1362): Kohana_ORM->check(NULL)
#1 C:\wamp\www\FreeAds\application\classes\Controller\users.php(94): Kohana_ORM->update()
#2 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(84): Controller_Users->action_updateprofil()
#3 [internal function]: Kohana_Controller->execute()
#4 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Users))
#5 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#6 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#7 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#8 {main} in C:\wamp\www\FreeAds\modules\orm\classes\Kohana\ORM.php:1362