<?php defined('SYSPATH') OR die('No direct script access.'); ?>

2013-10-23 11:43:58 --- CRITICAL: ORM_Validation_Exception [ 0 ]: Failed to validate array ~ MODPATH\orm\classes\Kohana\ORM.php [ 1275 ] in C:\wamp\www\FreeAds\modules\orm\classes\Kohana\ORM.php:1362
2013-10-23 11:43:58 --- DEBUG: #0 C:\wamp\www\FreeAds\modules\orm\classes\Kohana\ORM.php(1362): Kohana_ORM->check(NULL)
#1 C:\wamp\www\FreeAds\application\classes\Controller\users.php(104): Kohana_ORM->update()
#2 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(84): Controller_Users->action_updateprofil()
#3 [internal function]: Kohana_Controller->execute()
#4 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Users))
#5 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#6 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#7 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#8 {main} in C:\wamp\www\FreeAds\modules\orm\classes\Kohana\ORM.php:1362
2013-10-23 15:42:20 --- CRITICAL: ErrorException [ 8 ]: Trying to get property of non-object ~ APPPATH\views\pages\updateprofil.php [ 8 ] in C:\wamp\www\FreeAds\application\views\pages\updateprofil.php:8
2013-10-23 15:42:20 --- DEBUG: #0 C:\wamp\www\FreeAds\application\views\pages\updateprofil.php(8): Kohana_Core::error_handler(8, 'Trying to get p...', 'C:\wamp\www\Fre...', 8, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#2 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#3 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(228): Kohana_View->render()
#4 C:\wamp\www\FreeAds\application\views\template.php(129): Kohana_View->__toString()
#5 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#6 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#7 C:\wamp\www\FreeAds\system\classes\Kohana\Controller\Template.php(44): Kohana_View->render()
#8 C:\wamp\www\FreeAds\application\classes\Controller\demo.php(50): Kohana_Controller_Template->after()
#9 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(87): Controller_Demo->after()
#10 [internal function]: Kohana_Controller->execute()
#11 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Users))
#12 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#13 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#14 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#15 {main} in C:\wamp\www\FreeAds\application\views\pages\updateprofil.php:8
2013-10-23 19:29:37 --- CRITICAL: ErrorException [ 1 ]: Class 'Model_annonce' not found ~ MODPATH\orm\classes\Kohana\ORM.php [ 46 ] in file:line
2013-10-23 19:29:37 --- DEBUG: #0 [internal function]: Kohana_Core::shutdown_handler()
#1 {main} in file:line
2013-10-23 20:11:17 --- CRITICAL: ErrorException [ 4 ]: syntax error, unexpected 'public' (T_PUBLIC) ~ APPPATH\classes\Controller\annonces.php [ 51 ] in file:line
2013-10-23 20:11:17 --- DEBUG: #0 [internal function]: Kohana_Core::shutdown_handler()
#1 {main} in file:line
2013-10-23 21:56:37 --- CRITICAL: ErrorException [ 8 ]: Undefined variable: departements ~ APPPATH\views\pages\add.php [ 26 ] in C:\wamp\www\FreeAds\application\views\pages\add.php:26
2013-10-23 21:56:37 --- DEBUG: #0 C:\wamp\www\FreeAds\application\views\pages\add.php(26): Kohana_Core::error_handler(8, 'Undefined varia...', 'C:\wamp\www\Fre...', 26, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#2 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#3 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(228): Kohana_View->render()
#4 C:\wamp\www\FreeAds\application\views\template.php(130): Kohana_View->__toString()
#5 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#6 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#7 C:\wamp\www\FreeAds\system\classes\Kohana\Controller\Template.php(44): Kohana_View->render()
#8 C:\wamp\www\FreeAds\application\classes\Controller\demo.php(50): Kohana_Controller_Template->after()
#9 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(87): Controller_Demo->after()
#10 [internal function]: Kohana_Controller->execute()
#11 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Annonces))
#12 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#13 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#14 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#15 {main} in C:\wamp\www\FreeAds\application\views\pages\add.php:26
2013-10-23 21:57:42 --- CRITICAL: ErrorException [ 8 ]: Undefined variable: departements ~ APPPATH\views\pages\add.php [ 26 ] in C:\wamp\www\FreeAds\application\views\pages\add.php:26
2013-10-23 21:57:42 --- DEBUG: #0 C:\wamp\www\FreeAds\application\views\pages\add.php(26): Kohana_Core::error_handler(8, 'Undefined varia...', 'C:\wamp\www\Fre...', 26, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#2 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#3 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(228): Kohana_View->render()
#4 C:\wamp\www\FreeAds\application\views\template.php(130): Kohana_View->__toString()
#5 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#6 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#7 C:\wamp\www\FreeAds\system\classes\Kohana\Controller\Template.php(44): Kohana_View->render()
#8 C:\wamp\www\FreeAds\application\classes\Controller\demo.php(50): Kohana_Controller_Template->after()
#9 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(87): Controller_Demo->after()
#10 [internal function]: Kohana_Controller->execute()
#11 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Annonces))
#12 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#13 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#14 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#15 {main} in C:\wamp\www\FreeAds\application\views\pages\add.php:26
2013-10-23 21:57:44 --- CRITICAL: ErrorException [ 8 ]: Undefined variable: departements ~ APPPATH\views\pages\add.php [ 26 ] in C:\wamp\www\FreeAds\application\views\pages\add.php:26
2013-10-23 21:57:44 --- DEBUG: #0 C:\wamp\www\FreeAds\application\views\pages\add.php(26): Kohana_Core::error_handler(8, 'Undefined varia...', 'C:\wamp\www\Fre...', 26, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#2 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#3 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(228): Kohana_View->render()
#4 C:\wamp\www\FreeAds\application\views\template.php(130): Kohana_View->__toString()
#5 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#6 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#7 C:\wamp\www\FreeAds\system\classes\Kohana\Controller\Template.php(44): Kohana_View->render()
#8 C:\wamp\www\FreeAds\application\classes\Controller\demo.php(50): Kohana_Controller_Template->after()
#9 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(87): Controller_Demo->after()
#10 [internal function]: Kohana_Controller->execute()
#11 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Annonces))
#12 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#13 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#14 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#15 {main} in C:\wamp\www\FreeAds\application\views\pages\add.php:26
2013-10-23 21:58:04 --- CRITICAL: ErrorException [ 8 ]: Undefined variable: departements ~ APPPATH\views\pages\add.php [ 26 ] in C:\wamp\www\FreeAds\application\views\pages\add.php:26
2013-10-23 21:58:04 --- DEBUG: #0 C:\wamp\www\FreeAds\application\views\pages\add.php(26): Kohana_Core::error_handler(8, 'Undefined varia...', 'C:\wamp\www\Fre...', 26, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#2 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#3 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(228): Kohana_View->render()
#4 C:\wamp\www\FreeAds\application\views\template.php(130): Kohana_View->__toString()
#5 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#6 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#7 C:\wamp\www\FreeAds\system\classes\Kohana\Controller\Template.php(44): Kohana_View->render()
#8 C:\wamp\www\FreeAds\application\classes\Controller\demo.php(50): Kohana_Controller_Template->after()
#9 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(87): Controller_Demo->after()
#10 [internal function]: Kohana_Controller->execute()
#11 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Annonces))
#12 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#13 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#14 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#15 {main} in C:\wamp\www\FreeAds\application\views\pages\add.php:26
2013-10-23 21:58:07 --- CRITICAL: ErrorException [ 8 ]: Undefined variable: departements ~ APPPATH\views\pages\add.php [ 26 ] in C:\wamp\www\FreeAds\application\views\pages\add.php:26
2013-10-23 21:58:07 --- DEBUG: #0 C:\wamp\www\FreeAds\application\views\pages\add.php(26): Kohana_Core::error_handler(8, 'Undefined varia...', 'C:\wamp\www\Fre...', 26, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#2 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#3 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(228): Kohana_View->render()
#4 C:\wamp\www\FreeAds\application\views\template.php(130): Kohana_View->__toString()
#5 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#6 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#7 C:\wamp\www\FreeAds\system\classes\Kohana\Controller\Template.php(44): Kohana_View->render()
#8 C:\wamp\www\FreeAds\application\classes\Controller\demo.php(50): Kohana_Controller_Template->after()
#9 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(87): Controller_Demo->after()
#10 [internal function]: Kohana_Controller->execute()
#11 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Annonces))
#12 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#13 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#14 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#15 {main} in C:\wamp\www\FreeAds\application\views\pages\add.php:26
2013-10-23 21:59:07 --- CRITICAL: ErrorException [ 2 ]: Invalid argument supplied for foreach() ~ APPPATH\views\pages\add.php [ 26 ] in C:\wamp\www\FreeAds\application\views\pages\add.php:26
2013-10-23 21:59:07 --- DEBUG: #0 C:\wamp\www\FreeAds\application\views\pages\add.php(26): Kohana_Core::error_handler(2, 'Invalid argumen...', 'C:\wamp\www\Fre...', 26, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#2 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#3 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(228): Kohana_View->render()
#4 C:\wamp\www\FreeAds\application\views\template.php(130): Kohana_View->__toString()
#5 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#6 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#7 C:\wamp\www\FreeAds\system\classes\Kohana\Controller\Template.php(44): Kohana_View->render()
#8 C:\wamp\www\FreeAds\application\classes\Controller\demo.php(50): Kohana_Controller_Template->after()
#9 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(87): Controller_Demo->after()
#10 [internal function]: Kohana_Controller->execute()
#11 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Annonces))
#12 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#13 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#14 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#15 {main} in C:\wamp\www\FreeAds\application\views\pages\add.php:26
2013-10-23 22:01:00 --- CRITICAL: ErrorException [ 1 ]: Class 'Model_departement' not found ~ MODPATH\orm\classes\Kohana\ORM.php [ 46 ] in file:line
2013-10-23 22:01:00 --- DEBUG: #0 [internal function]: Kohana_Core::shutdown_handler()
#1 {main} in file:line
2013-10-23 22:02:59 --- CRITICAL: ErrorException [ 8 ]: Undefined variable: departements ~ APPPATH\views\pages\add.php [ 26 ] in C:\wamp\www\FreeAds\application\views\pages\add.php:26
2013-10-23 22:02:59 --- DEBUG: #0 C:\wamp\www\FreeAds\application\views\pages\add.php(26): Kohana_Core::error_handler(8, 'Undefined varia...', 'C:\wamp\www\Fre...', 26, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#2 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#3 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(228): Kohana_View->render()
#4 C:\wamp\www\FreeAds\application\views\template.php(130): Kohana_View->__toString()
#5 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#6 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#7 C:\wamp\www\FreeAds\system\classes\Kohana\Controller\Template.php(44): Kohana_View->render()
#8 C:\wamp\www\FreeAds\application\classes\Controller\demo.php(50): Kohana_Controller_Template->after()
#9 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(87): Controller_Demo->after()
#10 [internal function]: Kohana_Controller->execute()
#11 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Annonces))
#12 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#13 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#14 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#15 {main} in C:\wamp\www\FreeAds\application\views\pages\add.php:26
2013-10-23 22:03:16 --- CRITICAL: ErrorException [ 8 ]: Undefined variable: departements ~ APPPATH\views\pages\add.php [ 26 ] in C:\wamp\www\FreeAds\application\views\pages\add.php:26
2013-10-23 22:03:16 --- DEBUG: #0 C:\wamp\www\FreeAds\application\views\pages\add.php(26): Kohana_Core::error_handler(8, 'Undefined varia...', 'C:\wamp\www\Fre...', 26, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#2 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#3 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(228): Kohana_View->render()
#4 C:\wamp\www\FreeAds\application\views\template.php(130): Kohana_View->__toString()
#5 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#6 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#7 C:\wamp\www\FreeAds\system\classes\Kohana\Controller\Template.php(44): Kohana_View->render()
#8 C:\wamp\www\FreeAds\application\classes\Controller\demo.php(50): Kohana_Controller_Template->after()
#9 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(87): Controller_Demo->after()
#10 [internal function]: Kohana_Controller->execute()
#11 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Annonces))
#12 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#13 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#14 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#15 {main} in C:\wamp\www\FreeAds\application\views\pages\add.php:26
2013-10-23 22:04:47 --- CRITICAL: ErrorException [ 2 ]: Invalid argument supplied for foreach() ~ APPPATH\views\pages\add.php [ 26 ] in C:\wamp\www\FreeAds\application\views\pages\add.php:26
2013-10-23 22:04:47 --- DEBUG: #0 C:\wamp\www\FreeAds\application\views\pages\add.php(26): Kohana_Core::error_handler(2, 'Invalid argumen...', 'C:\wamp\www\Fre...', 26, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#2 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#3 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(228): Kohana_View->render()
#4 C:\wamp\www\FreeAds\application\views\template.php(130): Kohana_View->__toString()
#5 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#6 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#7 C:\wamp\www\FreeAds\system\classes\Kohana\Controller\Template.php(44): Kohana_View->render()
#8 C:\wamp\www\FreeAds\application\classes\Controller\demo.php(50): Kohana_Controller_Template->after()
#9 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(87): Controller_Demo->after()
#10 [internal function]: Kohana_Controller->execute()
#11 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Annonces))
#12 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#13 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#14 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#15 {main} in C:\wamp\www\FreeAds\application\views\pages\add.php:26
2013-10-23 22:07:31 --- CRITICAL: ErrorException [ 2 ]: Invalid argument supplied for foreach() ~ APPPATH\views\pages\add.php [ 26 ] in C:\wamp\www\FreeAds\application\views\pages\add.php:26
2013-10-23 22:07:31 --- DEBUG: #0 C:\wamp\www\FreeAds\application\views\pages\add.php(26): Kohana_Core::error_handler(2, 'Invalid argumen...', 'C:\wamp\www\Fre...', 26, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#2 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#3 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(228): Kohana_View->render()
#4 C:\wamp\www\FreeAds\application\views\template.php(130): Kohana_View->__toString()
#5 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#6 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#7 C:\wamp\www\FreeAds\system\classes\Kohana\Controller\Template.php(44): Kohana_View->render()
#8 C:\wamp\www\FreeAds\application\classes\Controller\demo.php(50): Kohana_Controller_Template->after()
#9 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(87): Controller_Demo->after()
#10 [internal function]: Kohana_Controller->execute()
#11 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Annonces))
#12 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#13 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#14 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#15 {main} in C:\wamp\www\FreeAds\application\views\pages\add.php:26
2013-10-23 22:07:34 --- CRITICAL: ErrorException [ 2 ]: Invalid argument supplied for foreach() ~ APPPATH\views\pages\add.php [ 26 ] in C:\wamp\www\FreeAds\application\views\pages\add.php:26
2013-10-23 22:07:34 --- DEBUG: #0 C:\wamp\www\FreeAds\application\views\pages\add.php(26): Kohana_Core::error_handler(2, 'Invalid argumen...', 'C:\wamp\www\Fre...', 26, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#2 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#3 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(228): Kohana_View->render()
#4 C:\wamp\www\FreeAds\application\views\template.php(130): Kohana_View->__toString()
#5 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#6 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#7 C:\wamp\www\FreeAds\system\classes\Kohana\Controller\Template.php(44): Kohana_View->render()
#8 C:\wamp\www\FreeAds\application\classes\Controller\demo.php(50): Kohana_Controller_Template->after()
#9 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(87): Controller_Demo->after()
#10 [internal function]: Kohana_Controller->execute()
#11 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Annonces))
#12 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#13 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#14 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#15 {main} in C:\wamp\www\FreeAds\application\views\pages\add.php:26
2013-10-23 22:07:39 --- CRITICAL: ErrorException [ 2 ]: Invalid argument supplied for foreach() ~ APPPATH\views\pages\add.php [ 26 ] in C:\wamp\www\FreeAds\application\views\pages\add.php:26
2013-10-23 22:07:39 --- DEBUG: #0 C:\wamp\www\FreeAds\application\views\pages\add.php(26): Kohana_Core::error_handler(2, 'Invalid argumen...', 'C:\wamp\www\Fre...', 26, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#2 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#3 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(228): Kohana_View->render()
#4 C:\wamp\www\FreeAds\application\views\template.php(130): Kohana_View->__toString()
#5 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#6 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#7 C:\wamp\www\FreeAds\system\classes\Kohana\Controller\Template.php(44): Kohana_View->render()
#8 C:\wamp\www\FreeAds\application\classes\Controller\demo.php(50): Kohana_Controller_Template->after()
#9 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(87): Controller_Demo->after()
#10 [internal function]: Kohana_Controller->execute()
#11 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Annonces))
#12 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#13 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#14 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#15 {main} in C:\wamp\www\FreeAds\application\views\pages\add.php:26
2013-10-23 22:09:46 --- CRITICAL: ErrorException [ 2 ]: Invalid argument supplied for foreach() ~ APPPATH\views\pages\add.php [ 26 ] in C:\wamp\www\FreeAds\application\views\pages\add.php:26
2013-10-23 22:09:46 --- DEBUG: #0 C:\wamp\www\FreeAds\application\views\pages\add.php(26): Kohana_Core::error_handler(2, 'Invalid argumen...', 'C:\wamp\www\Fre...', 26, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#2 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#3 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(228): Kohana_View->render()
#4 C:\wamp\www\FreeAds\application\views\template.php(130): Kohana_View->__toString()
#5 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#6 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#7 C:\wamp\www\FreeAds\system\classes\Kohana\Controller\Template.php(44): Kohana_View->render()
#8 C:\wamp\www\FreeAds\application\classes\Controller\demo.php(50): Kohana_Controller_Template->after()
#9 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(87): Controller_Demo->after()
#10 [internal function]: Kohana_Controller->execute()
#11 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Annonces))
#12 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#13 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#14 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#15 {main} in C:\wamp\www\FreeAds\application\views\pages\add.php:26
2013-10-23 22:13:14 --- CRITICAL: ErrorException [ 8 ]: Trying to get property of non-object ~ APPPATH\views\pages\add.php [ 26 ] in C:\wamp\www\FreeAds\application\views\pages\add.php:26
2013-10-23 22:13:14 --- DEBUG: #0 C:\wamp\www\FreeAds\application\views\pages\add.php(26): Kohana_Core::error_handler(8, 'Trying to get p...', 'C:\wamp\www\Fre...', 26, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#2 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#3 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(228): Kohana_View->render()
#4 C:\wamp\www\FreeAds\application\views\template.php(130): Kohana_View->__toString()
#5 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#6 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#7 C:\wamp\www\FreeAds\system\classes\Kohana\Controller\Template.php(44): Kohana_View->render()
#8 C:\wamp\www\FreeAds\application\classes\Controller\demo.php(50): Kohana_Controller_Template->after()
#9 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(87): Controller_Demo->after()
#10 [internal function]: Kohana_Controller->execute()
#11 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Annonces))
#12 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#13 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#14 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#15 {main} in C:\wamp\www\FreeAds\application\views\pages\add.php:26
2013-10-23 22:13:51 --- CRITICAL: ErrorException [ 8 ]: Trying to get property of non-object ~ APPPATH\views\pages\add.php [ 26 ] in C:\wamp\www\FreeAds\application\views\pages\add.php:26
2013-10-23 22:13:51 --- DEBUG: #0 C:\wamp\www\FreeAds\application\views\pages\add.php(26): Kohana_Core::error_handler(8, 'Trying to get p...', 'C:\wamp\www\Fre...', 26, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#2 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#3 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(228): Kohana_View->render()
#4 C:\wamp\www\FreeAds\application\views\template.php(130): Kohana_View->__toString()
#5 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#6 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#7 C:\wamp\www\FreeAds\system\classes\Kohana\Controller\Template.php(44): Kohana_View->render()
#8 C:\wamp\www\FreeAds\application\classes\Controller\demo.php(50): Kohana_Controller_Template->after()
#9 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(87): Controller_Demo->after()
#10 [internal function]: Kohana_Controller->execute()
#11 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Annonces))
#12 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#13 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#14 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#15 {main} in C:\wamp\www\FreeAds\application\views\pages\add.php:26
2013-10-23 22:14:26 --- CRITICAL: ErrorException [ 8 ]: Trying to get property of non-object ~ APPPATH\views\pages\add.php [ 26 ] in C:\wamp\www\FreeAds\application\views\pages\add.php:26
2013-10-23 22:14:26 --- DEBUG: #0 C:\wamp\www\FreeAds\application\views\pages\add.php(26): Kohana_Core::error_handler(8, 'Trying to get p...', 'C:\wamp\www\Fre...', 26, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#2 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#3 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(228): Kohana_View->render()
#4 C:\wamp\www\FreeAds\application\views\template.php(130): Kohana_View->__toString()
#5 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#6 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#7 C:\wamp\www\FreeAds\system\classes\Kohana\Controller\Template.php(44): Kohana_View->render()
#8 C:\wamp\www\FreeAds\application\classes\Controller\demo.php(50): Kohana_Controller_Template->after()
#9 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(87): Controller_Demo->after()
#10 [internal function]: Kohana_Controller->execute()
#11 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Annonces))
#12 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#13 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#14 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#15 {main} in C:\wamp\www\FreeAds\application\views\pages\add.php:26
2013-10-23 22:15:33 --- CRITICAL: ErrorException [ 8 ]: Trying to get property of non-object ~ APPPATH\views\pages\add.php [ 26 ] in C:\wamp\www\FreeAds\application\views\pages\add.php:26
2013-10-23 22:15:33 --- DEBUG: #0 C:\wamp\www\FreeAds\application\views\pages\add.php(26): Kohana_Core::error_handler(8, 'Trying to get p...', 'C:\wamp\www\Fre...', 26, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#2 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#3 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(228): Kohana_View->render()
#4 C:\wamp\www\FreeAds\application\views\template.php(130): Kohana_View->__toString()
#5 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#6 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#7 C:\wamp\www\FreeAds\system\classes\Kohana\Controller\Template.php(44): Kohana_View->render()
#8 C:\wamp\www\FreeAds\application\classes\Controller\demo.php(50): Kohana_Controller_Template->after()
#9 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(87): Controller_Demo->after()
#10 [internal function]: Kohana_Controller->execute()
#11 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Annonces))
#12 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#13 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#14 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#15 {main} in C:\wamp\www\FreeAds\application\views\pages\add.php:26
2013-10-23 22:19:36 --- CRITICAL: ErrorException [ 2 ]: Invalid argument supplied for foreach() ~ APPPATH\views\pages\add.php [ 26 ] in C:\wamp\www\FreeAds\application\views\pages\add.php:26
2013-10-23 22:19:36 --- DEBUG: #0 C:\wamp\www\FreeAds\application\views\pages\add.php(26): Kohana_Core::error_handler(2, 'Invalid argumen...', 'C:\wamp\www\Fre...', 26, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#2 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#3 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(228): Kohana_View->render()
#4 C:\wamp\www\FreeAds\application\views\template.php(130): Kohana_View->__toString()
#5 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(61): include('C:\wamp\www\Fre...')
#6 C:\wamp\www\FreeAds\system\classes\Kohana\View.php(348): Kohana_View::capture('C:\wamp\www\Fre...', Array)
#7 C:\wamp\www\FreeAds\system\classes\Kohana\Controller\Template.php(44): Kohana_View->render()
#8 C:\wamp\www\FreeAds\application\classes\Controller\demo.php(50): Kohana_Controller_Template->after()
#9 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(87): Controller_Demo->after()
#10 [internal function]: Kohana_Controller->execute()
#11 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Annonces))
#12 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#13 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#14 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#15 {main} in C:\wamp\www\FreeAds\application\views\pages\add.php:26
2013-10-23 22:24:03 --- CRITICAL: ErrorException [ 1 ]: Call to undefined method Model_Departement::findall() ~ APPPATH\classes\Controller\annonces.php [ 14 ] in file:line
2013-10-23 22:24:03 --- DEBUG: #0 [internal function]: Kohana_Core::shutdown_handler()
#1 {main} in file:line
2013-10-23 22:31:15 --- CRITICAL: ErrorException [ 8 ]: Undefined variable: name ~ APPPATH\classes\Controller\annonces.php [ 14 ] in C:\wamp\www\FreeAds\application\classes\Controller\annonces.php:14
2013-10-23 22:31:15 --- DEBUG: #0 C:\wamp\www\FreeAds\application\classes\Controller\annonces.php(14): Kohana_Core::error_handler(8, 'Undefined varia...', 'C:\wamp\www\Fre...', 14, Array)
#1 C:\wamp\www\FreeAds\system\classes\Kohana\Controller.php(84): Controller_Annonces->action_add()
#2 [internal function]: Kohana_Controller->execute()
#3 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client\Internal.php(97): ReflectionMethod->invoke(Object(Controller_Annonces))
#4 C:\wamp\www\FreeAds\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#5 C:\wamp\www\FreeAds\system\classes\Kohana\Request.php(986): Kohana_Request_Client->execute(Object(Request))
#6 C:\wamp\www\FreeAds\index.php(118): Kohana_Request->execute()
#7 {main} in C:\wamp\www\FreeAds\application\classes\Controller\annonces.php:14
2013-10-23 22:34:55 --- CRITICAL: ErrorException [ 1 ]: Call to undefined function get_type() ~ APPPATH\views\pages\add.php [ 25 ] in file:line
2013-10-23 22:34:55 --- DEBUG: #0 [internal function]: Kohana_Core::shutdown_handler()
#1 {main} in file:line
2013-10-23 22:36:39 --- CRITICAL: ErrorException [ 4 ]: syntax error, unexpected '}' ~ APPPATH\views\pages\add.php [ 31 ] in file:line
2013-10-23 22:36:39 --- DEBUG: #0 [internal function]: Kohana_Core::shutdown_handler()
#1 {main} in file:line
2013-10-23 22:36:55 --- CRITICAL: ErrorException [ 4 ]: syntax error, unexpected '}' ~ APPPATH\views\pages\add.php [ 33 ] in file:line
2013-10-23 22:36:55 --- DEBUG: #0 [internal function]: Kohana_Core::shutdown_handler()
#1 {main} in file:line